version: 0.0.{build}
skip_non_tags: true
image: Visual Studio 2017
init:
- ps: |
    $InfoVer = $env:APPVEYOR_REPO_TAG_NAME.TrimStart("v");
    $Ver = $InfoVer.Split("-")[0];
    Set-AppveyorBuildVariable -Name "InfomationalVersion" -Value $InfoVer
    Set-AppveyorBuildVariable -Name "FileVersion" -Value $Ver
    Update-AppveyorBuild -Version $InfoVer
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
- ps: .${env:APPVEYOR_BUILD_FOLDER}\AppVeyor\install.ps1
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(FileVersion)
  assembly_file_version: $(FileVersion)
  assembly_informational_version: $(InfomationalVersion)
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(FileVersion)
  package_version: $(InfomationalVersion)
  assembly_version: $(FileVersion)
  file_version: $(FileVersion)
  informational_version: $(InfomationalVersion)
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
environment:
  Settings_json:
    secure: 8h1VAILXo7t3UrEWt8G8SPqi4WPRw/T8T3e2oNnJXwBLHY8F9m2uCnYDPOIgTYYNnpHO6TGdACtqDudbmEGFXrS5wgrZRB1OdHKGc3CftC0SzMpsExIDtOQ6lIEU04hnYW5pKxrUm1fHXJDkzql47lKk7uOIAtqRHxK7wjZnUO178tWkf1MZyoU9EiOjjB6KkZGHwLx2fB8hc5ZendLAVEshISCuVbOyRgZZxzCBH/pmG9FwHANbelJiW3vUOjKCgOmKSLygwiqNUawrzuPQ7+4Edi+qqf07if7GiAYM69gfhUJp3AJKyo2bAQJSKcuQFGK7F5gb7caqe6mwosjmssukz26x13yjzKtuhOKXXtE=
  TEST_SECRET:
    secure: psHf9gzh1NdoPBovCWs+VzQL9AILX7vy+tD73K6gjkMFHHxeFSGU0iChiPAMRqwH
  NuGetToken:
    secure: 8U0FY4Wh+zyJriYPpUsyFXTmoc+upnrqrV3+u5mEkBCttmytqIqk3hQe475ck5aJ
  APPVEYOR_RDP_PASSWORD:
    secure: ffiKvwUIVY4Ps169F1N1Uw==
test_script:
- ps: .${env:APPVEYOR_BUILD_FOLDER}\AppVeyor\test_script.ps1
artifacts:
- path: psCheckPoint.zip